<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
	<artifactId>entity-relationships-solution</artifactId>
	<packaging>war</packaging>
	<name>Configure Relationships web app Project</name>
	<description>This is the entity relationships project.</description>
	<parent>
		<groupId>com.redhat.training</groupId>
		<artifactId>parent-pom</artifactId>
		<version>1.0</version>
		<relativePath>../pom.xml</relativePath>
	</parent>

	<properties>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
	</properties>

    <finalName>entity-relationships</finalName>
        <plugins>
            <plugin>
                <artifactId>maven-war-plugin</artifactId>
				<version>${version.war.plugin}</version>
				<extensions>false</extensions>
			</plugin>
		</plugins>
	</build>

	<profiles>
		<profile>
			<!-- I've decided to leave this profile alone for the sake of learning. -->
			<!-- But it is not necessary at all to activate it, now follows the original authors comments. -->

			<!-- This profile skips all tests, though you can tune it to run just
				unit tests based on a custom pattern -->
			<!-- Separate profiles are provided for running all tests, including Arquillian
				tests that execute in the specified container -->
			<!-- Use this profile if you just want to build a WAR file without running
				any unit tests -->
			<!-- Run like this: mvn clean package -Pdefault -->
			<id>default</id>
			<build>
				<plugins>
					<plugin>
						<artifactId>maven-surefire-plugin</artifactId>
						<version>${version.surefire.plugin}</version>
						<configuration>
							<skip>true</skip>
						</configuration>
					</plugin>
				</plugins>
			</build>
		</profile>
	</profiles>
</project>
